Repository mvnueloc/DevInterview, pull requests merged in 2024-07, with the labels that each got.

#14 Componentes: Se agrego la Navbar y el Footer (Temporal)
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/common/MobileMenu.jsx
  src/components/icons/Discord.jsx
  src/components/icons/Github.jsx
  src/components/icons/Logo.jsx
  src/pages/Main.jsx
Labels: component

#15 Pagina: Se agrego la página de practicar.
  src/App.jsx
  src/components/Practicar/CardCategoria.jsx
  src/components/Practicar/Dificultad.jsx
  src/components/icons/Back-End/docker.png
  src/components/icons/Back-End/git.png
  src/components/icons/Back-End/node.png
  src/components/icons/Back-End/python.png
  src/components/icons/Back-End/sql.png
  src/components/icons/Front-End/angular.png
  src/components/icons/Front-End/css.png
  src/components/icons/Front-End/html.png
  src/components/icons/Front-End/javaScript.png
  src/components/icons/Front-End/react.png
  src/components/icons/Full-Stack/express.png
  src/components/icons/Full-Stack/git.png
  src/components/icons/Full-Stack/mongo.png
  src/components/icons/Full-Stack/node.png
  src/components/icons/Full-Stack/react.png
  src/components/icons/Software Developer/c++.png
  src/components/icons/Software Developer/git.png
  src/components/icons/Software Developer/pytest.png
  src/components/icons/Software Developer/python.png
  src/components/icons/Software Developer/sql.png
  src/pages/Main.jsx
  src/pages/Practicar.jsx
Labels: page

#18 Design: Se mejoro parcialmente el Index
  index.html
  public/images/stats-example.png
  src/components/main/ApiInfo.jsx
  src/components/main/ElementInfo.jsx
  src/components/main/Informacion.jsx
  src/components/main/Modelo.jsx
  src/pages/Main.jsx
  src/pages/styles/index.css
  tailwind.config.js
Labels: enhancement, component
